language: python
python:
  - "2.7"
services: mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies
install: 
  - pip install coverage
  - pip install python-coveralls
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests --with-coverage --cover-package=mf
after_success:
  - coveralls
